language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- 2.7

before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- source $HOME/.cargo/env

deploy:
  provider: rubygems
  api_key: $API_KEY
  gem: RackMiddlewareMetrics
  on:
    tags: true
    repo: reedjosh/RackMiddlewareMetrics
  skip_cleanup: 'true'
