[package]
name = "md5_ruby_ext"
version = "0.1.0"
authors = ["Reed, Joshua <joshua.reed@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
