source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in md5_ruby_ext.gemspec
gemspec

gem "solargraph", "~> 0.39.17"

gem "rake", "~> 10.5"

gem "rspec", "~> 3.9"
